### ISSUE TITLE
提个小建议：delete上下间距不太一样hhhh；挺有趣的小项目

### ISSUE THREAD

**Issue by Phil-Fan** [27chrisx/27chrisx.github.io#1]

**Comment by Phil-Fan** [comment]
提个小建议：delete上下间距不太一样hhhh；挺有趣的小项目

**Comment by jiajunzhuchris** [comment]
谢谢来信，项目后续会继续改进，感谢您的支持




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "27chrisx/Todo-list"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月28日(星期五) 凌晨1:31
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [27chrisx/Todo-list] 提个小建议 (Issue #1)





 
提个小建议：delete上下间距不太一样hhhh；挺有趣的小项目
