### ISSUE TITLE
关于TodoList的记忆和存储功能

### ISSUE THREAD

**Issue by MinJoker** [27chrisx/27chrisx.github.io#2]
网页刷新之后用户的操作全部都消失了，看来这个TodoList没有记忆和存储功能。
（我不是很清楚静态网页是否方便做这样的事情）或许可以尝试把用户的操作存储在云端（多人协作同一个TodoList，怪），或者把个人用户的操作存储在本地之类的。

**Comment by jiajunzhuchris** [comment]
收到建议，目前此项目仅仅是一个联系coding能力的独立笑网页，后续可能会弄一个账号记录机制来将每个对应的人制作的数据储存到云端以供日常使用，感谢您的支持

**Comment by MinJoker** [comment]
> 

浅浅期待一下~
